//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34003
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comment.
        /// </summary>
        internal static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string dateComment {
            get {
                return ResourceManager.GetString("dateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string dateRecommendation {
            get {
                return ResourceManager.GetString("dateRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comment.
        /// </summary>
        internal static string eventComment {
            get {
                return ResourceManager.GetString("eventComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Event Date.
        /// </summary>
        internal static string eventDate {
            get {
                return ResourceManager.GetString("eventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        internal static string eventID {
            get {
                return ResourceManager.GetString("eventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group description.
        /// </summary>
        internal static string groupDescription {
            get {
                return ResourceManager.GetString("groupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        internal static string groupId {
            get {
                return ResourceManager.GetString("groupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group name.
        /// </summary>
        internal static string groupName {
            get {
                return ResourceManager.GetString("groupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Groups.
        /// </summary>
        internal static string groups {
            get {
                return ResourceManager.GetString("groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keywords.
        /// </summary>
        internal static string keywordsEvents {
            get {
                return ResourceManager.GetString("keywordsEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mandatory Field.
        /// </summary>
        internal static string mandatoryField {
            get {
                return ResourceManager.GetString("mandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category.
        /// </summary>
        internal static string nameCategory {
            get {
                return ResourceManager.GetString("nameCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string nameEvent {
            get {
                return ResourceManager.GetString("nameEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NºMembers.
        /// </summary>
        internal static string numMembers {
            get {
                return ResourceManager.GetString("numMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NºRecommendations.
        /// </summary>
        internal static string numRecommendations {
            get {
                return ResourceManager.GetString("numRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recommend.
        /// </summary>
        internal static string recommend {
            get {
                return ResourceManager.GetString("recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Event.
        /// </summary>
        internal static string sportEventName {
            get {
                return ResourceManager.GetString("sportEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subscribe.
        /// </summary>
        internal static string subscribe {
            get {
                return ResourceManager.GetString("subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tags.
        /// </summary>
        internal static string tags {
            get {
                return ResourceManager.GetString("tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unsubscribe.
        /// </summary>
        internal static string unsubscribe {
            get {
                return ResourceManager.GetString("unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string userProfile {
            get {
                return ResourceManager.GetString("userProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string userProfileName {
            get {
                return ResourceManager.GetString("userProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View Comments.
        /// </summary>
        internal static string viewComments {
            get {
                return ResourceManager.GetString("viewComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reason.
        /// </summary>
        internal static string why {
            get {
                return ResourceManager.GetString("why", resourceCulture);
            }
        }
    }
}
