//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.SportsNow.Model", "FK_SportEvent_Category", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Es.Udc.DotNet.SportsNow.Model.Category), "SportEvent", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.SportsNow.Model.SportEvent))]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.SportsNow.Model", "FK_Comment_SportEvent", "SportEvent", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.SportsNow.Model.SportEvent), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.SportsNow.Model.Comment))]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.SportsNow.Model", "FK_Comment_UserProfile", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.SportsNow.Model.UserProfile), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.SportsNow.Model.Comment))]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.SportsNow.Model", "FK_Recommendation_SportEvent", "SportEvent", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.SportsNow.Model.SportEvent), "Recommendation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.SportsNow.Model.Recommendation))]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.SportsNow.Model", "FK_Recommendation_UserProfile", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.SportsNow.Model.UserProfile), "Recommendation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.SportsNow.Model.Recommendation))]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.SportsNow.Model", "CommentTag", "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.SportsNow.Model.Comment), "Tag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.SportsNow.Model.Tag))]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.SportsNow.Model", "RecommendationUserGroup", "Recommendation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.SportsNow.Model.Recommendation), "UserGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.SportsNow.Model.UserGroup))]
[assembly: EdmRelationshipAttribute("Es.Udc.DotNet.SportsNow.Model", "UserProfileUserGroup", "UserGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.SportsNow.Model.UserGroup), "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.SportsNow.Model.UserProfile))]

#endregion

namespace Es.Udc.DotNet.SportsNow.Model
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class SportsNowEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto SportsNowEntities usando la cadena de conexión encontrada en la sección 'SportsNowEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public SportsNowEntities() : base("name=SportsNowEntities", "SportsNowEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SportsNowEntities.
        /// </summary>
        public SportsNowEntities(string connectionString) : base(connectionString, "SportsNowEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SportsNowEntities.
        /// </summary>
        public SportsNowEntities(EntityConnection connection) : base(connection, "SportsNowEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Comment> Comments
        {
            get
            {
                if ((_Comments == null))
                {
                    _Comments = base.CreateObjectSet<Comment>("Comments");
                }
                return _Comments;
            }
        }
        private ObjectSet<Comment> _Comments;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Recommendation> Recommendations
        {
            get
            {
                if ((_Recommendations == null))
                {
                    _Recommendations = base.CreateObjectSet<Recommendation>("Recommendations");
                }
                return _Recommendations;
            }
        }
        private ObjectSet<Recommendation> _Recommendations;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<SportEvent> SportEvents
        {
            get
            {
                if ((_SportEvents == null))
                {
                    _SportEvents = base.CreateObjectSet<SportEvent>("SportEvents");
                }
                return _SportEvents;
            }
        }
        private ObjectSet<SportEvent> _SportEvents;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Tag> Tags
        {
            get
            {
                if ((_Tags == null))
                {
                    _Tags = base.CreateObjectSet<Tag>("Tags");
                }
                return _Tags;
            }
        }
        private ObjectSet<Tag> _Tags;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<UserGroup> UserGroups
        {
            get
            {
                if ((_UserGroups == null))
                {
                    _UserGroups = base.CreateObjectSet<UserGroup>("UserGroups");
                }
                return _UserGroups;
            }
        }
        private ObjectSet<UserGroup> _UserGroups;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<UserProfile> UserProfiles
        {
            get
            {
                if ((_UserProfiles == null))
                {
                    _UserProfiles = base.CreateObjectSet<UserProfile>("UserProfiles");
                }
                return _UserProfiles;
            }
        }
        private ObjectSet<UserProfile> _UserProfiles;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Categories. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Comments. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToComments(Comment comment)
        {
            base.AddObject("Comments", comment);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Recommendations. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToRecommendations(Recommendation recommendation)
        {
            base.AddObject("Recommendations", recommendation);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet SportEvents. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToSportEvents(SportEvent sportEvent)
        {
            base.AddObject("SportEvents", sportEvent);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Tags. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTags(Tag tag)
        {
            base.AddObject("Tags", tag);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet UserGroups. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUserGroups(UserGroup userGroup)
        {
            base.AddObject("UserGroups", userGroup);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet UserProfiles. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUserProfiles(UserProfile userProfile)
        {
            base.AddObject("UserProfiles", userProfile);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.SportsNow.Model", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Category.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        public static Category CreateCategory(global::System.Int64 id, global::System.String name)
        {
            Category category = new Category();
            category.id = id;
            category.name = name;
            return category;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.SportsNow.Model", "FK_SportEvent_Category", "SportEvent")]
        public EntityCollection<SportEvent> SportEvents
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SportEvent>("Es.Udc.DotNet.SportsNow.Model.FK_SportEvent_Category", "SportEvent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SportEvent>("Es.Udc.DotNet.SportsNow.Model.FK_SportEvent_Category", "SportEvent", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.SportsNow.Model", Name="Comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comment : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Comment.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="value">Valor inicial de la propiedad value.</param>
        /// <param name="dateComment">Valor inicial de la propiedad dateComment.</param>
        public static Comment CreateComment(global::System.Int64 id, global::System.String value, global::System.DateTime dateComment)
        {
            Comment comment = new Comment();
            comment.id = id;
            comment.value = value;
            comment.dateComment = dateComment;
            return comment;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateComment
        {
            get
            {
                return _dateComment;
            }
            set
            {
                OndateCommentChanging(value);
                ReportPropertyChanging("dateComment");
                _dateComment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateComment");
                OndateCommentChanged();
            }
        }
        private global::System.DateTime _dateComment;
        partial void OndateCommentChanging(global::System.DateTime value);
        partial void OndateCommentChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.SportsNow.Model", "FK_Comment_SportEvent", "SportEvent")]
        public SportEvent SportEvent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SportEvent>("Es.Udc.DotNet.SportsNow.Model.FK_Comment_SportEvent", "SportEvent").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SportEvent>("Es.Udc.DotNet.SportsNow.Model.FK_Comment_SportEvent", "SportEvent").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SportEvent> SportEventReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SportEvent>("Es.Udc.DotNet.SportsNow.Model.FK_Comment_SportEvent", "SportEvent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SportEvent>("Es.Udc.DotNet.SportsNow.Model.FK_Comment_SportEvent", "SportEvent", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.SportsNow.Model", "FK_Comment_UserProfile", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.SportsNow.Model.FK_Comment_UserProfile", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.SportsNow.Model.FK_Comment_UserProfile", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.SportsNow.Model.FK_Comment_UserProfile", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("Es.Udc.DotNet.SportsNow.Model.FK_Comment_UserProfile", "UserProfile", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.SportsNow.Model", "CommentTag", "Tag")]
        public EntityCollection<Tag> Tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tag>("Es.Udc.DotNet.SportsNow.Model.CommentTag", "Tag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tag>("Es.Udc.DotNet.SportsNow.Model.CommentTag", "Tag", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.SportsNow.Model", Name="Recommendation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Recommendation : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Recommendation.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="dateRecommendation">Valor inicial de la propiedad dateRecommendation.</param>
        /// <param name="why">Valor inicial de la propiedad why.</param>
        public static Recommendation CreateRecommendation(global::System.Int64 id, global::System.DateTime dateRecommendation, global::System.String why)
        {
            Recommendation recommendation = new Recommendation();
            recommendation.id = id;
            recommendation.dateRecommendation = dateRecommendation;
            recommendation.why = why;
            return recommendation;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateRecommendation
        {
            get
            {
                return _dateRecommendation;
            }
            set
            {
                OndateRecommendationChanging(value);
                ReportPropertyChanging("dateRecommendation");
                _dateRecommendation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateRecommendation");
                OndateRecommendationChanged();
            }
        }
        private global::System.DateTime _dateRecommendation;
        partial void OndateRecommendationChanging(global::System.DateTime value);
        partial void OndateRecommendationChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String why
        {
            get
            {
                return _why;
            }
            set
            {
                OnwhyChanging(value);
                ReportPropertyChanging("why");
                _why = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("why");
                OnwhyChanged();
            }
        }
        private global::System.String _why;
        partial void OnwhyChanging(global::System.String value);
        partial void OnwhyChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.SportsNow.Model", "FK_Recommendation_SportEvent", "SportEvent")]
        public SportEvent SportEvent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SportEvent>("Es.Udc.DotNet.SportsNow.Model.FK_Recommendation_SportEvent", "SportEvent").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SportEvent>("Es.Udc.DotNet.SportsNow.Model.FK_Recommendation_SportEvent", "SportEvent").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SportEvent> SportEventReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SportEvent>("Es.Udc.DotNet.SportsNow.Model.FK_Recommendation_SportEvent", "SportEvent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SportEvent>("Es.Udc.DotNet.SportsNow.Model.FK_Recommendation_SportEvent", "SportEvent", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.SportsNow.Model", "FK_Recommendation_UserProfile", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.SportsNow.Model.FK_Recommendation_UserProfile", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.SportsNow.Model.FK_Recommendation_UserProfile", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("Es.Udc.DotNet.SportsNow.Model.FK_Recommendation_UserProfile", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("Es.Udc.DotNet.SportsNow.Model.FK_Recommendation_UserProfile", "UserProfile", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.SportsNow.Model", "RecommendationUserGroup", "UserGroup")]
        public EntityCollection<UserGroup> UserGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserGroup>("Es.Udc.DotNet.SportsNow.Model.RecommendationUserGroup", "UserGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserGroup>("Es.Udc.DotNet.SportsNow.Model.RecommendationUserGroup", "UserGroup", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.SportsNow.Model", Name="SportEvent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SportEvent : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto SportEvent.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        /// <param name="dateEvent">Valor inicial de la propiedad dateEvent.</param>
        /// <param name="place">Valor inicial de la propiedad place.</param>
        /// <param name="review">Valor inicial de la propiedad review.</param>
        public static SportEvent CreateSportEvent(global::System.Int64 id, global::System.String name, global::System.DateTime dateEvent, global::System.String place, global::System.String review)
        {
            SportEvent sportEvent = new SportEvent();
            sportEvent.id = id;
            sportEvent.name = name;
            sportEvent.dateEvent = dateEvent;
            sportEvent.place = place;
            sportEvent.review = review;
            return sportEvent;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateEvent
        {
            get
            {
                return _dateEvent;
            }
            set
            {
                OndateEventChanging(value);
                ReportPropertyChanging("dateEvent");
                _dateEvent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateEvent");
                OndateEventChanged();
            }
        }
        private global::System.DateTime _dateEvent;
        partial void OndateEventChanging(global::System.DateTime value);
        partial void OndateEventChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String place
        {
            get
            {
                return _place;
            }
            set
            {
                OnplaceChanging(value);
                ReportPropertyChanging("place");
                _place = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("place");
                OnplaceChanged();
            }
        }
        private global::System.String _place;
        partial void OnplaceChanging(global::System.String value);
        partial void OnplaceChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String review
        {
            get
            {
                return _review;
            }
            set
            {
                OnreviewChanging(value);
                ReportPropertyChanging("review");
                _review = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("review");
                OnreviewChanged();
            }
        }
        private global::System.String _review;
        partial void OnreviewChanging(global::System.String value);
        partial void OnreviewChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.SportsNow.Model", "FK_SportEvent_Category", "Category")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("Es.Udc.DotNet.SportsNow.Model.FK_SportEvent_Category", "Category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("Es.Udc.DotNet.SportsNow.Model.FK_SportEvent_Category", "Category").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("Es.Udc.DotNet.SportsNow.Model.FK_SportEvent_Category", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("Es.Udc.DotNet.SportsNow.Model.FK_SportEvent_Category", "Category", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.SportsNow.Model", "FK_Comment_SportEvent", "Comment")]
        public EntityCollection<Comment> Comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comment>("Es.Udc.DotNet.SportsNow.Model.FK_Comment_SportEvent", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comment>("Es.Udc.DotNet.SportsNow.Model.FK_Comment_SportEvent", "Comment", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.SportsNow.Model", "FK_Recommendation_SportEvent", "Recommendation")]
        public EntityCollection<Recommendation> Recommendations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Recommendation>("Es.Udc.DotNet.SportsNow.Model.FK_Recommendation_SportEvent", "Recommendation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Recommendation>("Es.Udc.DotNet.SportsNow.Model.FK_Recommendation_SportEvent", "Recommendation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.SportsNow.Model", Name="Tag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tag : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Tag.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        public static Tag CreateTag(global::System.Int64 id, global::System.String name)
        {
            Tag tag = new Tag();
            tag.id = id;
            tag.name = name;
            return tag;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.SportsNow.Model", "CommentTag", "Comment")]
        public EntityCollection<Comment> Comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comment>("Es.Udc.DotNet.SportsNow.Model.CommentTag", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comment>("Es.Udc.DotNet.SportsNow.Model.CommentTag", "Comment", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.SportsNow.Model", Name="UserGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserGroup : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto UserGroup.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        /// <param name="descrip">Valor inicial de la propiedad descrip.</param>
        public static UserGroup CreateUserGroup(global::System.Int64 id, global::System.String name, global::System.String descrip)
        {
            UserGroup userGroup = new UserGroup();
            userGroup.id = id;
            userGroup.name = name;
            userGroup.descrip = descrip;
            return userGroup;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descrip
        {
            get
            {
                return _descrip;
            }
            set
            {
                OndescripChanging(value);
                ReportPropertyChanging("descrip");
                _descrip = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descrip");
                OndescripChanged();
            }
        }
        private global::System.String _descrip;
        partial void OndescripChanging(global::System.String value);
        partial void OndescripChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.SportsNow.Model", "RecommendationUserGroup", "Recommendation")]
        public EntityCollection<Recommendation> Recommendations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Recommendation>("Es.Udc.DotNet.SportsNow.Model.RecommendationUserGroup", "Recommendation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Recommendation>("Es.Udc.DotNet.SportsNow.Model.RecommendationUserGroup", "Recommendation", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.SportsNow.Model", "UserProfileUserGroup", "UserProfile")]
        public EntityCollection<UserProfile> UserProfiles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserProfile>("Es.Udc.DotNet.SportsNow.Model.UserProfileUserGroup", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserProfile>("Es.Udc.DotNet.SportsNow.Model.UserProfileUserGroup", "UserProfile", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.SportsNow.Model", Name="UserProfile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserProfile : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto UserProfile.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="loginName">Valor inicial de la propiedad loginName.</param>
        /// <param name="enPassword">Valor inicial de la propiedad enPassword.</param>
        /// <param name="firstName">Valor inicial de la propiedad firstName.</param>
        /// <param name="lastName">Valor inicial de la propiedad lastName.</param>
        /// <param name="email">Valor inicial de la propiedad email.</param>
        /// <param name="language">Valor inicial de la propiedad language.</param>
        /// <param name="country">Valor inicial de la propiedad country.</param>
        public static UserProfile CreateUserProfile(global::System.Int64 id, global::System.String loginName, global::System.String enPassword, global::System.String firstName, global::System.String lastName, global::System.String email, global::System.String language, global::System.String country)
        {
            UserProfile userProfile = new UserProfile();
            userProfile.id = id;
            userProfile.loginName = loginName;
            userProfile.enPassword = enPassword;
            userProfile.firstName = firstName;
            userProfile.lastName = lastName;
            userProfile.email = email;
            userProfile.language = language;
            userProfile.country = country;
            return userProfile;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String loginName
        {
            get
            {
                return _loginName;
            }
            set
            {
                OnloginNameChanging(value);
                ReportPropertyChanging("loginName");
                _loginName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("loginName");
                OnloginNameChanged();
            }
        }
        private global::System.String _loginName;
        partial void OnloginNameChanging(global::System.String value);
        partial void OnloginNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String enPassword
        {
            get
            {
                return _enPassword;
            }
            set
            {
                OnenPasswordChanging(value);
                ReportPropertyChanging("enPassword");
                _enPassword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("enPassword");
                OnenPasswordChanged();
            }
        }
        private global::System.String _enPassword;
        partial void OnenPasswordChanging(global::System.String value);
        partial void OnenPasswordChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String language
        {
            get
            {
                return _language;
            }
            set
            {
                OnlanguageChanging(value);
                ReportPropertyChanging("language");
                _language = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("language");
                OnlanguageChanged();
            }
        }
        private global::System.String _language;
        partial void OnlanguageChanging(global::System.String value);
        partial void OnlanguageChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String country
        {
            get
            {
                return _country;
            }
            set
            {
                OncountryChanging(value);
                ReportPropertyChanging("country");
                _country = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("country");
                OncountryChanged();
            }
        }
        private global::System.String _country;
        partial void OncountryChanging(global::System.String value);
        partial void OncountryChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.SportsNow.Model", "FK_Comment_UserProfile", "Comment")]
        public EntityCollection<Comment> Comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comment>("Es.Udc.DotNet.SportsNow.Model.FK_Comment_UserProfile", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comment>("Es.Udc.DotNet.SportsNow.Model.FK_Comment_UserProfile", "Comment", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.SportsNow.Model", "FK_Recommendation_UserProfile", "Recommendation")]
        public EntityCollection<Recommendation> Recommendations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Recommendation>("Es.Udc.DotNet.SportsNow.Model.FK_Recommendation_UserProfile", "Recommendation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Recommendation>("Es.Udc.DotNet.SportsNow.Model.FK_Recommendation_UserProfile", "Recommendation", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.SportsNow.Model", "UserProfileUserGroup", "UserGroup")]
        public EntityCollection<UserGroup> UserGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserGroup>("Es.Udc.DotNet.SportsNow.Model.UserProfileUserGroup", "UserGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserGroup>("Es.Udc.DotNet.SportsNow.Model.UserProfileUserGroup", "UserGroup", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
